#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    arr=sorted(arr)
    print(sum(arr[:-1]),sum(arr[1:]))
    # Write your code here

if __name__ == '__main__':

    arr = [int(i) for i in input().split()]

    miniMaxSum(arr)
